name: Go

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: stable
    - run: go build -v ./...
    - run: go test -v -race ./...
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
